networks:
  app_net:
    driver: bridge

services:
  django-app:
    build: .
    container_name: ${DJANGO_CONTAINER_NAME:-django-app}
    restart: always
    env_file:
      - path: .env  #Doklpoy environment variables
    volumes:
      - media_data:/app/data/media    # Persist uploaded media files
      - static_data:/app/data/static  # Persist collected static files
    healthcheck:  # Healthcheck to ensure the service is up
      test: ["CMD", "curl", "-f", "http://localhost/api/?format=json"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
        - app_net
    ports:
      - ${DJANGO_EXTERNAL_PORT:-8002}:${DJANGO_INTERNAL_PORT:-8000}

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    env_file:
      - path: .env  #Doklpoy environment variables
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Use the custom Nginx config
      - media_data:/app/data/media
      - static_data:/app/data/static
    networks:
      - app_net
    ports:
      - ${NGINX_EXTERNAL_PORT:-8011}:${NGINX_INTERNAL_PORT:-8001}

volumes:
  db_data:
  media_data:
  static_data: