networks:
  app_net:
    driver: bridge

services:
  django-app:
    build: .
    #container_name: ${DJANGO_CONTAINER_NAME:-django-app} # Disabled: Dokploy
    restart: always
    env_file:
      - path: .env
    volumes:
      - db_data:/app/data/db          # Persist SQLite database file
      - media_data:/app/data/media    # Persist uploaded media files
      - static_data:/app/data/static  # Persist collected static files
    networks:
        - app_net
    healthcheck:  # Healthcheck to ensure the service is up
      test: ["CMD", "curl", "-f", "http://django-app:8000"]
      interval: 30s
      timeout: 10s
      retries: 3


  nginx:
    image: nginx:latest
    #container_name: ${NGINX_CONTAINER_NAME:-nginx-test} # Disabled: Dokploy
    restart: always
    env_file:
      - path: .env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro            # Config file
      - media_data:/app/data/media                              # Media files directory
      - static_data:/app/data/static                            # Static files directory
    networks:
      - app_net
    ports:
      - ${NGINX_PORT:-8001}:80 # Map the Nginx port
    depends_on:
      - django-app

volumes:
  db_data:
  media_data:
  static_data: