networks:
  app_net:
    driver: bridge

services:
  django-app:
    build: .
    container_name: django-app
    restart: always
    env_file:
      - ${DJANGO_ENV_FILE:-.env.django.dev}  # Dynamically load .env.dev or .env.prod
    volumes:
      - db_data:/app/data/db          # Persist SQLite database file
      - media_data:/app/data/media    # Persist uploaded media files
      - static_data:/app/data/static  # Persist collected static files
    networks:
        - app_net
    healthcheck:  # Healthcheck to ensure the service is up
      test: ["CMD", "curl", "-f", "${DJANGO_HEALTH_CHECK_URL:-http://localhost:8000}"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "${NGINX_PORT:-8001}:80"  # Map the Nginx port
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro            # Config file
      - media_data:/app/data/media                              # Media files directory
      - static_data:/app/data/static                            # Static files directory
    env_file:
      - ${NGINX_ENV_FILE:-.env.nginx.dev}  # Dynamically load .env.dev or .env.prod
    networks:
      - app_net

volumes:
  db_data:
  media_data:
  static_data:
