services:
  web:
    build: .
    container_name: django_app
    restart: always
    env_file:
      - ${DJANGO_ENV_FILE:-.env.dev}  # Dynamically load .env.dev or .env.prod
    volumes:
      - media_data:/app/data/media    # Persist uploaded media files
      - static_data:/app/data/static  # Persist collected static files
    depends_on:
      - nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/?format=json"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: >
      sh -c "
      python manage.py collectstatic --noinput &&
      python manage.py migrate --noinput &&
      gunicorn myapp.wsgi:application --bind 0.0.0.0:8000
      "

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Use the custom Nginx config
      - media_data:/app/data/media
      - static_data:/app/data/static

volumes:
  media_data:
  static_data: