services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:80"  # Ändere den externen Host-Port auf 8080
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_data:/app/data/static
      - media_data:/app/data/media
    depends_on:
      - django_app

  django_app:
    build: .
    container_name: django_app
    restart: always
    ports:
      - "8001:8000"  # Ändere den externen Host-Port auf 8001
    environment:
      DJANGO_SETTINGS_MODULE: "B2B_Backend.settings"
    depends_on:
      - db

volumes:
  static_data:
  media_data: